alias sudo="sudo "
alias s="sudo "
alias c="clear"
alias emacs="emacs -nw"
alias e="emacs -nw"
alias grep="grep --color=auto"
alias g="grep --color=auto"
alias l="ls -altr"
alias ..="cd .."
alias -- -="cd -"
alias pgrep="pgrep -i"